name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
      
    - name: Setup Swift
      uses: fwal/setup-swift@v1.7.0

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

      #- name: Show what's in Applications
      #run: ls -al /Applications

      #- name: Switch to Xcode 11
      #run: sudo xcode-select -s /Applications/Xcode_11.3.1.app

    - name: swift-format-lint
      uses: Iron-Ham/swift-format-linter-action@v5

    - name: build and test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
