name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
      
    - name: Setup Swift
      uses: fwal/setup-swift@v1.7.0

    - name: Homebrew build helpers install
      run: brew bundle

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

      #- name: Show what's in Applications
      #run: ls -al /Applications

      #- name: Switch to Xcode 11
      #run: sudo xcode-select -s /Applications/Xcode_11.3.1.app

    - name: Show Build Settings
      run: xcodebuild -workspace MPCF-TestBench.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -workspace MPCF-TestBench.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showsdks

    - name: Show Available Destinations
      run: xcodebuild -workspace MPCF-TestBench.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    - name: lint
      run: swift format lint --configuration .swift-format-config -r .

    - name: build and test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
